# Generated by Django 4.0.3 on 2022-04-01 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenttweet',
            name='img',
            field=models.ImageField(blank=True, upload_to='tweets/comment-tweets/%Y/%M/%D'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='img',
            field=models.ImageField(blank=True, upload_to='tweets/%Y/%M/%D'),
        ),
    ]
