# Generated by Django 4.0.3 on 2022-04-03 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_alter_commenttweet_img_alter_tweet_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenttweet',
            name='img',
            field=models.ImageField(blank=True, upload_to='tweets/comment-tweets/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='img',
            field=models.ImageField(blank=True, upload_to='tweets/%Y/%m/%d/'),
        ),
    ]
