# Generated by Django 4.0.3 on 2022-04-10 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_myuser_pp'),
        ('tweets', '0004_remove_commenttweet_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='date',
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweets.commenttweet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.myuser')),
            ],
        ),
    ]
