# Generated by Django 4.0.3 on 2022-04-11 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_myuser_pp'),
        ('tweets', '0005_remove_like_date_commentlike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='tweet',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='commenttweet',
            name='likes',
        ),
        migrations.AddField(
            model_name='commenttweet',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='comment_likes', to='main.myuser'),
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='likes',
        ),
        migrations.AddField(
            model_name='tweet',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='tweet_likes', to='main.myuser'),
        ),
        migrations.DeleteModel(
            name='CommentLike',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
